package com.carrer.ats_parser;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.http.*;
import org.apache.tika.Tika;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.ListItem;
import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.Arrays;

@Controller
public class HelloController {

    @GetMapping("/")
    public String showUploadPage() {
        return "index";
    }

    @PostMapping("/upload")
    public String handleFileUpload(@RequestParam("file") MultipartFile file,
                                   @RequestParam("jobDescription") String jobDescription,
                                   Model model) {
        if (file.isEmpty()) {
            model.addAttribute("error", "Please select a file.");
            return "index";
        }

        try {
            Tika tika = new Tika();
            String resumeText = tika.parseToString(file.getInputStream()).toLowerCase();
            String jobDescLower = jobDescription.toLowerCase();

            // Keywords updated to match your Java & AI focus
            String[] keywords = {
                    "java", "spring", "sql", "maven", "rest", "api", "git", "docker", "aws",
                    "python", "artificial intelligence", "problem-solving", "analyze", "hibernate"
            };

            int totalKeywordsInJD = 0;
            int matches = 0;
            // Using full path to avoid conflict with com.itextpdf.layout.element.List
            java.util.List<String> matchedSkills = new java.util.ArrayList<>();
            java.util.List<String> missingSkills = new java.util.ArrayList<>();

            for (String skill : keywords) {
                if (jobDescLower.contains(skill)) {
                    totalKeywordsInJD++;
                    if (resumeText.contains(skill)) {
                        matches++;
                        matchedSkills.add(skill);
                    } else {
                        missingSkills.add(skill);
                    }
                }
            }

            int finalScore = (totalKeywordsInJD > 0) ? (matches * 100 / totalKeywordsInJD) : 0;

            model.addAttribute("score", finalScore);
            model.addAttribute("fileName", file.getOriginalFilename());
            model.addAttribute("matched", String.join(", ", matchedSkills));
            model.addAttribute("missing", String.join(", ", missingSkills));

            return "result";

        } catch (Exception e) {
            model.addAttribute("error", "Error during analysis: " + e.getMessage());
            return "index";
        }
    }

    @GetMapping("/download")
    public ResponseEntity<byte[]> downloadReport(@RequestParam int score,
                                                 @RequestParam String name,
                                                 @RequestParam(required = false) String matched) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            PdfWriter writer = new PdfWriter(out);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);

            document.add(new Paragraph("Smart ATS Analysis Report").setBold().setFontSize(24));
            document.add(new Paragraph("Candidate Resume: " + name));
            document.add(new Paragraph("Job Match Score: " + score + "%"));

            if (matched != null && !matched.isEmpty()) {
                document.add(new Paragraph("\nSkills Identified:").setBold());
                document.add(new Paragraph(matched));
            }

            document.add(new Paragraph("\nGenerated by: Durga Prasad's AI Parser"));
            document.close();

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=ATS_Report.pdf")
                    .contentType(MediaType.APPLICATION_PDF)
                    .body(out.toByteArray());
        } catch (Exception e) {
            return ResponseEntity.internalServerError().build();
        }
    }
}